# Generated by Django 4.2.27 on 2025-12-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('et_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
