# Generated by Django 5.2.8 on 2025-11-30 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('et_transactions', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='et_transactions.category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='percentage',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Store as a whole number (e.g., 82.50 for 82.5%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='budget',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='et_transactions.category'),
        ),
    ]
